### ISSUE TITLE
Get error for naming print in Command.php file, use Command namespace because the name is already in annot use Illuminate\Console\Command as Command because the name is already in ModelConnect, ModelDetail. 

### ISSUE THREAD

**Issue by permatis** [flipboxstudio/orm-manager#2]
- First

 i get error ''Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'print' (T_PRINT), expecting identifier (T_STRING)' in `flipbox\orm-manager\src\Flipbox\OrmManager\Consoles\Command.php:120`'

- Second

 i get error "Cannot use Illuminate\Console\Command as Command because the name is already in use in `flipbox\orm-manager\src\Flipbox\OrmManager\Consoles\ModelDetail.php:5`" and same for `flipbox\orm-manager\src\Flipbox\OrmManager\Consoles\ModelConnect.php:7`

- Third

 i get error "Syntax error, unexpected '->' (T_OBJECT_OPERATOR)' in `flipbox\orm-manager\src\Flipbox\OrmManager\Consoles\ModelDetail.php:178`.

- And the Last 

i get error "Unknown database type json requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it."

**Comment by denmasyarikin** [comment]
hy there, thanks for your report, 
i has pushed some change to solve that all,
can you manual install in branch 0.0.2-beta, before i release this?
or your contribution are welcome..

**Comment by denmasyarikin** [comment]
I think it's solved by commit #008c89f and previose one, and i has been released 0.0.2-beta, thanks

**Comment by permatis** [comment]
hi, sorry too late for replying.
I've replaced change your code manually. I just change name in function and using a namespace. For function like `print` function, i change to `printing` function. Because i think `print` function use globlally. And then change all them use this function. For using ` Illuminate\Console\Command` namespace i just add alias to `use Illuminate\Console\Command as Commands` and replace use this namespace. 
For error `Syntax error, unexpected '->' (T_OBJECT_OPERATOR)'`, i just remove `->count()` using `count()` function, like this `count($mutators = &$properties['mutators'])`.

ok sir. thanks. 
btw, what if the added feature to generate the property table and fillable in models.

**Comment by denmasyarikin** [comment]
Nice idea bro,
I'm so glad, if you interested to develop that feature
